//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TechnicalServiceReference.Service1Soap")]
    public interface Service1Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTcallProcedure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.DTcallProcedureResponseDTcallProcedureResult DTcallProcedure(string nombreProcedimiento, object[] argumentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DTcallProcedure", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.DTcallProcedureResponseDTcallProcedureResult> DTcallProcedureAsync(string nombreProcedimiento, object[] argumentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DScallProcedure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement DScallProcedure(string nombreProcedure, object[] argumentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DScallProcedure", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> DScallProcedureAsync(string nombreProcedure, object[] argumentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VOIDcallProcedure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void VOIDcallProcedure(string nombreProcedure, object[] argumentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VOIDcallProcedure", ReplyAction="*")]
        System.Threading.Tasks.Task VOIDcallProcedureAsync(string nombreProcedure, object[] argumentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StringCallFunction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string StringCallFunction(string nombreFunction, object[] argumentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StringCallFunction", ReplyAction="*")]
        System.Threading.Tasks.Task<string> StringCallFunctionAsync(string nombreFunction, object[] argumentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DateCallFunction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.DateTime DateCallFunction(string nombreFunction, object[] argumentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DateCallFunction", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> DateCallFunctionAsync(string nombreFunction, object[] argumentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IntCallFunction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int IntCallFunction(string nombreFunction, object[] argumentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IntCallFunction", ReplyAction="*")]
        System.Threading.Tasks.Task<int> IntCallFunctionAsync(string nombreFunction, object[] argumentos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_facturacion2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        double sp_facturacion2(double v_fact_id, double v_clie_llave, string v_user_id, double v_mesa_id, string v_fact_fecha, string v_fact_factura, string v_fact_tipo_serv, string v_mozo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_facturacion2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> sp_facturacion2Async(double v_fact_id, double v_clie_llave, string v_user_id, double v_mesa_id, string v_fact_fecha, string v_fact_factura, string v_fact_tipo_serv, string v_mozo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_consulta_caja2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_consulta_caja2(string tipo, string usuario, string sucursal, string fechadesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_consulta_caja2", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_consulta_caja2Async(string tipo, string usuario, string sucursal, string fechadesde, string fechaHasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reporte_producto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement reporte_producto(int tipo_consulta, int pi_producto, int pi_marca, int pi_laboratorio, string pi_desde, string pi_hasta, string pi_checkvencimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/reporte_producto", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> reporte_productoAsync(int tipo_consulta, int pi_producto, int pi_marca, int pi_laboratorio, string pi_desde, string pi_hasta, string pi_checkvencimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_consulta_caja", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_consulta_caja(string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_consulta_caja", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_consulta_cajaAsync(string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_permiso_objetos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_permiso_objetos(string pi_tipo, string pi_usuario, string pi_pantalla, string pi_objeto, string pi_sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_permiso_objetos", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_permiso_objetosAsync(string pi_tipo, string pi_usuario, string pi_pantalla, string pi_objeto, string pi_sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscacliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement buscacliente(string tipo, string documento, string codigocliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscacliente", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> buscaclienteAsync(string tipo, string documento, string codigocliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_consuta_compra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_consuta_compra(string pi_tipo, string pi_nrolote, System.DateTime pi_fechadesde, System.DateTime pi_fechahasta, string pi_parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_consuta_compra", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_consuta_compraAsync(string pi_tipo, string pi_nrolote, System.DateTime pi_fechadesde, System.DateTime pi_fechahasta, string pi_parametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_control_venta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_control_venta(string pi_tipo, string pi_usuario, string pi_codproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_control_venta", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_control_ventaAsync(string pi_tipo, string pi_usuario, string pi_codproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_cuadre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_cuadre(string pi_tipo, string pi_sucursal, string pi_usuario, System.DateTime pi_desde, System.DateTime pi_hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_cuadre", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_cuadreAsync(string pi_tipo, string pi_sucursal, string pi_usuario, System.DateTime pi_desde, System.DateTime pi_hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_datos_factura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_datos_factura(double v_factura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_datos_factura", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_datos_facturaAsync(double v_factura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_apertura_caja", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_apertura_caja(string pi_tipo, string pi_inout, string pi_suc, double pi_monto, double pi_descuento, double pi_pordescuento, string pi_concepto, string pi_cliente, string pi_usuario, string pi_motivo, string pi_comprobante, string pi_fechavenci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_apertura_caja", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_apertura_cajaAsync(string pi_tipo, string pi_inout, string pi_suc, double pi_monto, double pi_descuento, double pi_pordescuento, string pi_concepto, string pi_cliente, string pi_usuario, string pi_motivo, string pi_comprobante, string pi_fechavenci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_carga_laboratorio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_carga_laboratorio(string tipo_proceso, string id_codigo, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_carga_laboratorio", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_carga_laboratorioAsync(string tipo_proceso, string id_codigo, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_confirma_factura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_confirma_factura(double v_efectivo, double v_cheque, double v_chequenro, string v_banco, double v_tarjeta, double v_tarjetanro, string v_tarjetatipo, string v_tarjetaafinidad, double v_descuento, double v_factura, double v_mesa, string v_mozo, string v_nro_factura, double v_cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_confirma_factura", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_confirma_facturaAsync(double v_efectivo, double v_cheque, double v_chequenro, string v_banco, double v_tarjeta, double v_tarjetanro, string v_tarjetatipo, string v_tarjetaafinidad, double v_descuento, double v_factura, double v_mesa, string v_mozo, string v_nro_factura, double v_cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_elimina_detalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_elimina_detalle(double v_id, double v_id_facutra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_elimina_detalle", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_elimina_detalleAsync(double v_id, double v_id_facutra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_get_datos_varios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_get_datos_varios(string pi_id_empresa, string pi_timbrado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_get_datos_varios", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_get_datos_variosAsync(string pi_id_empresa, string pi_timbrado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inserta_producto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string inserta_producto(
                    string tipoproceso, 
                    int codigopro, 
                    string tipoprodu, 
                    string marca, 
                    string nombre, 
                    decimal precioc, 
                    decimal preciov, 
                    double mamahouseo, 
                    string nomenclatura, 
                    decimal iva, 
                    decimal preciov2, 
                    decimal preciov3, 
                    int PI_LABORATORIO, 
                    string PI_CODIGOPRODUCTO, 
                    string PI_CODIGO_BARRA, 
                    string PI_NROLOTE, 
                    string PI_VENCIMIENTO, 
                    string PI_COMPOSICION, 
                    string PI_CONTROLADO, 
                    string PI_FRACCION, 
                    int PI_CANTCAJA, 
                    int PI_DESCUENTO, 
                    string PI_FINDESCUENTO, 
                    string PI_USUARIO, 
                    string pi_codproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inserta_producto", ReplyAction="*")]
        System.Threading.Tasks.Task<string> inserta_productoAsync(
                    string tipoproceso, 
                    int codigopro, 
                    string tipoprodu, 
                    string marca, 
                    string nombre, 
                    decimal precioc, 
                    decimal preciov, 
                    double mamahouseo, 
                    string nomenclatura, 
                    decimal iva, 
                    decimal preciov2, 
                    decimal preciov3, 
                    int PI_LABORATORIO, 
                    string PI_CODIGOPRODUCTO, 
                    string PI_CODIGO_BARRA, 
                    string PI_NROLOTE, 
                    string PI_VENCIMIENTO, 
                    string PI_COMPOSICION, 
                    string PI_CONTROLADO, 
                    string PI_FRACCION, 
                    int PI_CANTCAJA, 
                    int PI_DESCUENTO, 
                    string PI_FINDESCUENTO, 
                    string PI_USUARIO, 
                    string pi_codproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_busqueda_cliente001", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_busqueda_cliente001(string v_tipo, double v_codigo, string v_documento, string v_nombre, string v_apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_busqueda_cliente001", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_busqueda_cliente001Async(string v_tipo, double v_codigo, string v_documento, string v_nombre, string v_apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_mozos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_mozos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_mozos", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_mozosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_datos_producto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_datos_producto(double v_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_datos_producto", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_datos_productoAsync(double v_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_validacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_validacion(string PI_TIPO, string PI_CODPRODUCTO, string PI_CODBARRA, string PI_FECHA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_validacion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_validacionAsync(string PI_TIPO, string PI_CODPRODUCTO, string PI_CODBARRA, string PI_FECHA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inserta_tipo_marca", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string inserta_tipo_marca(string tipo_proceso, string id_codigo, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inserta_tipo_marca", ReplyAction="*")]
        System.Threading.Tasks.Task<string> inserta_tipo_marcaAsync(string tipo_proceso, string id_codigo, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inserta_tipo_producto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string inserta_tipo_producto(string tipo_proceso, string id_codigo, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inserta_tipo_producto", ReplyAction="*")]
        System.Threading.Tasks.Task<string> inserta_tipo_productoAsync(string tipo_proceso, string id_codigo, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertupdatecliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string insertupdatecliente(string tipoproceso, string codigocliente, string nombre, string apellido, string tipo_persona, string documento, string direccion, string telefono, string email, string fechanaci, string sexo, string operarconche, string refname, string reftelef, string profesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertupdatecliente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> insertupdateclienteAsync(string tipoproceso, string codigocliente, string nombre, string apellido, string tipo_persona, string documento, string direccion, string telefono, string email, string fechanaci, string sexo, string operarconche, string refname, string reftelef, string profesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_validaciones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_validaciones(string pi_tipo, string pi_parametro, string pi_sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_validaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_validacionesAsync(string pi_tipo, string pi_parametro, string pi_sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/marcarpresencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void marcarpresencia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/marcarpresencia", ReplyAction="*")]
        System.Threading.Tasks.Task marcarpresenciaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_actualizaNombreFactura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_actualizaNombreFactura(string pi_tipo, string cliente, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_actualizaNombreFactura", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_actualizaNombreFacturaAsync(string pi_tipo, string cliente, string comprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_consulta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_consulta(string tipo, string datoin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_consulta", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_consultaAsync(string tipo, string datoin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_anular_factura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_anular_factura(double v_factura, double v_mesa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_anular_factura", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_anular_facturaAsync(double v_factura, double v_mesa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_combos_sistema", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_combos_sistema(string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_combos_sistema", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_combos_sistemaAsync(string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_datos_pedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_datos_pedido();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_datos_pedido", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_datos_pedidoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_datos_producto1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_datos_producto1(double v_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_datos_producto1", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_datos_producto1Async(double v_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_get_timbrados_ventas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_get_timbrados_ventas(string pi_id_empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_get_timbrados_ventas", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_get_timbrados_ventasAsync(string pi_id_empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_historico_caja", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_historico_caja(string v_desde, string v_hasta, string v_estado, string v_tipo, string V_SUCURSAL, string V_USUARIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_historico_caja", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_historico_cajaAsync(string v_desde, string v_hasta, string v_estado, string v_tipo, string V_SUCURSAL, string V_USUARIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_inserta_detalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_inserta_detalle(double v_fact_id, double v_produ_id, double v_menu_id, double v_fdet_cantidad, string v_fdet_descri, double v_fdet_descp, double v_fdet_descm, double v_fdet_preciou, double v_fdet_preciot, double v_fdet_ivatip, double v_fdet_gravado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_inserta_detalle", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_inserta_detalleAsync(double v_fact_id, double v_produ_id, double v_menu_id, double v_fdet_cantidad, string v_fdet_descri, double v_fdet_descp, double v_fdet_descm, double v_fdet_preciou, double v_fdet_preciot, double v_fdet_ivatip, double v_fdet_gravado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_inserta_detalle2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_inserta_detalle2(double v_fact_id, double v_produ_id, double v_menu_id, double v_fdet_cantidad, string v_fdet_descri, double v_fdet_descp, double v_fdet_descm, double v_fdet_preciou, double v_fdet_preciot, double v_fdet_ivatip, double v_fdet_gravado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_inserta_detalle2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_inserta_detalle2Async(double v_fact_id, double v_produ_id, double v_menu_id, double v_fdet_cantidad, string v_fdet_descri, double v_fdet_descp, double v_fdet_descm, double v_fdet_preciou, double v_fdet_preciot, double v_fdet_ivatip, double v_fdet_gravado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SP_LISTA_COMPRAS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement SP_LISTA_COMPRAS(string PI_TIPO, string PI_CODPRODUCTO, string PI_DESDE, string PI_HASTA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SP_LISTA_COMPRAS", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> SP_LISTA_COMPRASAsync(string PI_TIPO, string PI_CODPRODUCTO, string PI_DESDE, string PI_HASTA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_listado_categorias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_listado_categorias(string pi_tipo, string pi_codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_listado_categorias", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_listado_categoriasAsync(string pi_tipo, string pi_codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_reporte_producto1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_reporte_producto1(int tipo_consulta, double pi_producto, double pi_marca, string pi_descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_reporte_producto1", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_reporte_producto1Async(int tipo_consulta, double pi_producto, double pi_marca, string pi_descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_perdidas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void sp_perdidas(string pi_tipo, string pi_codproducto, string pi_cantidadactual, string pi_cantidadnueva, string pi_diferencia, string pi_sucursal, string pi_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_perdidas", ReplyAction="*")]
        System.Threading.Tasks.Task sp_perdidasAsync(string pi_tipo, string pi_codproducto, string pi_cantidadactual, string pi_cantidadnueva, string pi_diferencia, string pi_sucursal, string pi_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/f_usuario_login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        double f_usuario_login(string pi_usuario, string pi_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/f_usuario_login", ReplyAction="*")]
        System.Threading.Tasks.Task<double> f_usuario_loginAsync(string pi_usuario, string pi_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SP_MENSAJE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string SP_MENSAJE(string pi_cliente, string pi_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SP_MENSAJE", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SP_MENSAJEAsync(string pi_cliente, string pi_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_usuario_sel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_usuario_sel(string v_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_usuario_sel", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_usuario_selAsync(string v_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_usuario_updpas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        double sp_usuario_updpas(string pi_usuario, string pi_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_usuario_updpas", ReplyAction="*")]
        System.Threading.Tasks.Task<double> sp_usuario_updpasAsync(string pi_usuario, string pi_password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_usuario(string pi_tipo, string pi_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_usuarioAsync(string pi_tipo, string pi_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_lista_facturas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_lista_facturas(string v_desde, string v_hasta, string v_tipo, string usuario, string sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_lista_facturas", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_lista_facturasAsync(string v_desde, string v_hasta, string v_tipo, string usuario, string sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_tipos_usuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_tipos_usuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_tipos_usuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_tipos_usuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_estados_usuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_estados_usuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_estados_usuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_estados_usuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_lista_usuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        TechnicalServiceReference.ArrayOfXElement sp_lista_usuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_lista_usuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_lista_usuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_usuario_ins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_usuario_ins(string pi_usuario, string pi_apellido, string pi_password, string pi_cedula, int pi_nivel, string pi_telef, int pi_estado, string sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_usuario_ins", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_usuario_insAsync(string pi_usuario, string pi_apellido, string pi_password, string pi_cedula, int pi_nivel, string pi_telef, int pi_estado, string sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_usuario_upd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string sp_usuario_upd(string pi_usuario, string pi_apellido, string pi_password, string pi_cedula, int pi_nivel, string pi_telef, int pi_estado, string sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sp_usuario_upd", ReplyAction="*")]
        System.Threading.Tasks.Task<string> sp_usuario_updAsync(string pi_usuario, string pi_apellido, string pi_password, string pi_cedula, int pi_nivel, string pi_telef, int pi_estado, string sucursal);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class DTcallProcedureResponseDTcallProcedureResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface Service1SoapChannel : TechnicalServiceReference.Service1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<TechnicalServiceReference.Service1Soap>, TechnicalServiceReference.Service1Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), Service1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public TechnicalServiceReference.DTcallProcedureResponseDTcallProcedureResult DTcallProcedure(string nombreProcedimiento, object[] argumentos)
        {
            return base.Channel.DTcallProcedure(nombreProcedimiento, argumentos);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.DTcallProcedureResponseDTcallProcedureResult> DTcallProcedureAsync(string nombreProcedimiento, object[] argumentos)
        {
            return base.Channel.DTcallProcedureAsync(nombreProcedimiento, argumentos);
        }
        
        public TechnicalServiceReference.ArrayOfXElement DScallProcedure(string nombreProcedure, object[] argumentos)
        {
            return base.Channel.DScallProcedure(nombreProcedure, argumentos);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> DScallProcedureAsync(string nombreProcedure, object[] argumentos)
        {
            return base.Channel.DScallProcedureAsync(nombreProcedure, argumentos);
        }
        
        public void VOIDcallProcedure(string nombreProcedure, object[] argumentos)
        {
            base.Channel.VOIDcallProcedure(nombreProcedure, argumentos);
        }
        
        public System.Threading.Tasks.Task VOIDcallProcedureAsync(string nombreProcedure, object[] argumentos)
        {
            return base.Channel.VOIDcallProcedureAsync(nombreProcedure, argumentos);
        }
        
        public string StringCallFunction(string nombreFunction, object[] argumentos)
        {
            return base.Channel.StringCallFunction(nombreFunction, argumentos);
        }
        
        public System.Threading.Tasks.Task<string> StringCallFunctionAsync(string nombreFunction, object[] argumentos)
        {
            return base.Channel.StringCallFunctionAsync(nombreFunction, argumentos);
        }
        
        public System.DateTime DateCallFunction(string nombreFunction, object[] argumentos)
        {
            return base.Channel.DateCallFunction(nombreFunction, argumentos);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> DateCallFunctionAsync(string nombreFunction, object[] argumentos)
        {
            return base.Channel.DateCallFunctionAsync(nombreFunction, argumentos);
        }
        
        public int IntCallFunction(string nombreFunction, object[] argumentos)
        {
            return base.Channel.IntCallFunction(nombreFunction, argumentos);
        }
        
        public System.Threading.Tasks.Task<int> IntCallFunctionAsync(string nombreFunction, object[] argumentos)
        {
            return base.Channel.IntCallFunctionAsync(nombreFunction, argumentos);
        }
        
        public double sp_facturacion2(double v_fact_id, double v_clie_llave, string v_user_id, double v_mesa_id, string v_fact_fecha, string v_fact_factura, string v_fact_tipo_serv, string v_mozo)
        {
            return base.Channel.sp_facturacion2(v_fact_id, v_clie_llave, v_user_id, v_mesa_id, v_fact_fecha, v_fact_factura, v_fact_tipo_serv, v_mozo);
        }
        
        public System.Threading.Tasks.Task<double> sp_facturacion2Async(double v_fact_id, double v_clie_llave, string v_user_id, double v_mesa_id, string v_fact_fecha, string v_fact_factura, string v_fact_tipo_serv, string v_mozo)
        {
            return base.Channel.sp_facturacion2Async(v_fact_id, v_clie_llave, v_user_id, v_mesa_id, v_fact_fecha, v_fact_factura, v_fact_tipo_serv, v_mozo);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_consulta_caja2(string tipo, string usuario, string sucursal, string fechadesde, string fechaHasta)
        {
            return base.Channel.sp_consulta_caja2(tipo, usuario, sucursal, fechadesde, fechaHasta);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_consulta_caja2Async(string tipo, string usuario, string sucursal, string fechadesde, string fechaHasta)
        {
            return base.Channel.sp_consulta_caja2Async(tipo, usuario, sucursal, fechadesde, fechaHasta);
        }
        
        public TechnicalServiceReference.ArrayOfXElement reporte_producto(int tipo_consulta, int pi_producto, int pi_marca, int pi_laboratorio, string pi_desde, string pi_hasta, string pi_checkvencimiento)
        {
            return base.Channel.reporte_producto(tipo_consulta, pi_producto, pi_marca, pi_laboratorio, pi_desde, pi_hasta, pi_checkvencimiento);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> reporte_productoAsync(int tipo_consulta, int pi_producto, int pi_marca, int pi_laboratorio, string pi_desde, string pi_hasta, string pi_checkvencimiento)
        {
            return base.Channel.reporte_productoAsync(tipo_consulta, pi_producto, pi_marca, pi_laboratorio, pi_desde, pi_hasta, pi_checkvencimiento);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_consulta_caja(string tipo)
        {
            return base.Channel.sp_consulta_caja(tipo);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_consulta_cajaAsync(string tipo)
        {
            return base.Channel.sp_consulta_cajaAsync(tipo);
        }
        
        public string sp_permiso_objetos(string pi_tipo, string pi_usuario, string pi_pantalla, string pi_objeto, string pi_sucursal)
        {
            return base.Channel.sp_permiso_objetos(pi_tipo, pi_usuario, pi_pantalla, pi_objeto, pi_sucursal);
        }
        
        public System.Threading.Tasks.Task<string> sp_permiso_objetosAsync(string pi_tipo, string pi_usuario, string pi_pantalla, string pi_objeto, string pi_sucursal)
        {
            return base.Channel.sp_permiso_objetosAsync(pi_tipo, pi_usuario, pi_pantalla, pi_objeto, pi_sucursal);
        }
        
        public TechnicalServiceReference.ArrayOfXElement buscacliente(string tipo, string documento, string codigocliente)
        {
            return base.Channel.buscacliente(tipo, documento, codigocliente);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> buscaclienteAsync(string tipo, string documento, string codigocliente)
        {
            return base.Channel.buscaclienteAsync(tipo, documento, codigocliente);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_consuta_compra(string pi_tipo, string pi_nrolote, System.DateTime pi_fechadesde, System.DateTime pi_fechahasta, string pi_parametro)
        {
            return base.Channel.sp_consuta_compra(pi_tipo, pi_nrolote, pi_fechadesde, pi_fechahasta, pi_parametro);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_consuta_compraAsync(string pi_tipo, string pi_nrolote, System.DateTime pi_fechadesde, System.DateTime pi_fechahasta, string pi_parametro)
        {
            return base.Channel.sp_consuta_compraAsync(pi_tipo, pi_nrolote, pi_fechadesde, pi_fechahasta, pi_parametro);
        }
        
        public string sp_control_venta(string pi_tipo, string pi_usuario, string pi_codproducto)
        {
            return base.Channel.sp_control_venta(pi_tipo, pi_usuario, pi_codproducto);
        }
        
        public System.Threading.Tasks.Task<string> sp_control_ventaAsync(string pi_tipo, string pi_usuario, string pi_codproducto)
        {
            return base.Channel.sp_control_ventaAsync(pi_tipo, pi_usuario, pi_codproducto);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_cuadre(string pi_tipo, string pi_sucursal, string pi_usuario, System.DateTime pi_desde, System.DateTime pi_hasta)
        {
            return base.Channel.sp_cuadre(pi_tipo, pi_sucursal, pi_usuario, pi_desde, pi_hasta);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_cuadreAsync(string pi_tipo, string pi_sucursal, string pi_usuario, System.DateTime pi_desde, System.DateTime pi_hasta)
        {
            return base.Channel.sp_cuadreAsync(pi_tipo, pi_sucursal, pi_usuario, pi_desde, pi_hasta);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_datos_factura(double v_factura)
        {
            return base.Channel.sp_datos_factura(v_factura);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_datos_facturaAsync(double v_factura)
        {
            return base.Channel.sp_datos_facturaAsync(v_factura);
        }
        
        public string sp_apertura_caja(string pi_tipo, string pi_inout, string pi_suc, double pi_monto, double pi_descuento, double pi_pordescuento, string pi_concepto, string pi_cliente, string pi_usuario, string pi_motivo, string pi_comprobante, string pi_fechavenci)
        {
            return base.Channel.sp_apertura_caja(pi_tipo, pi_inout, pi_suc, pi_monto, pi_descuento, pi_pordescuento, pi_concepto, pi_cliente, pi_usuario, pi_motivo, pi_comprobante, pi_fechavenci);
        }
        
        public System.Threading.Tasks.Task<string> sp_apertura_cajaAsync(string pi_tipo, string pi_inout, string pi_suc, double pi_monto, double pi_descuento, double pi_pordescuento, string pi_concepto, string pi_cliente, string pi_usuario, string pi_motivo, string pi_comprobante, string pi_fechavenci)
        {
            return base.Channel.sp_apertura_cajaAsync(pi_tipo, pi_inout, pi_suc, pi_monto, pi_descuento, pi_pordescuento, pi_concepto, pi_cliente, pi_usuario, pi_motivo, pi_comprobante, pi_fechavenci);
        }
        
        public string sp_carga_laboratorio(string tipo_proceso, string id_codigo, string nombre)
        {
            return base.Channel.sp_carga_laboratorio(tipo_proceso, id_codigo, nombre);
        }
        
        public System.Threading.Tasks.Task<string> sp_carga_laboratorioAsync(string tipo_proceso, string id_codigo, string nombre)
        {
            return base.Channel.sp_carga_laboratorioAsync(tipo_proceso, id_codigo, nombre);
        }
        
        public string sp_confirma_factura(double v_efectivo, double v_cheque, double v_chequenro, string v_banco, double v_tarjeta, double v_tarjetanro, string v_tarjetatipo, string v_tarjetaafinidad, double v_descuento, double v_factura, double v_mesa, string v_mozo, string v_nro_factura, double v_cliente)
        {
            return base.Channel.sp_confirma_factura(v_efectivo, v_cheque, v_chequenro, v_banco, v_tarjeta, v_tarjetanro, v_tarjetatipo, v_tarjetaafinidad, v_descuento, v_factura, v_mesa, v_mozo, v_nro_factura, v_cliente);
        }
        
        public System.Threading.Tasks.Task<string> sp_confirma_facturaAsync(double v_efectivo, double v_cheque, double v_chequenro, string v_banco, double v_tarjeta, double v_tarjetanro, string v_tarjetatipo, string v_tarjetaafinidad, double v_descuento, double v_factura, double v_mesa, string v_mozo, string v_nro_factura, double v_cliente)
        {
            return base.Channel.sp_confirma_facturaAsync(v_efectivo, v_cheque, v_chequenro, v_banco, v_tarjeta, v_tarjetanro, v_tarjetatipo, v_tarjetaafinidad, v_descuento, v_factura, v_mesa, v_mozo, v_nro_factura, v_cliente);
        }
        
        public string sp_elimina_detalle(double v_id, double v_id_facutra)
        {
            return base.Channel.sp_elimina_detalle(v_id, v_id_facutra);
        }
        
        public System.Threading.Tasks.Task<string> sp_elimina_detalleAsync(double v_id, double v_id_facutra)
        {
            return base.Channel.sp_elimina_detalleAsync(v_id, v_id_facutra);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_get_datos_varios(string pi_id_empresa, string pi_timbrado)
        {
            return base.Channel.sp_get_datos_varios(pi_id_empresa, pi_timbrado);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_get_datos_variosAsync(string pi_id_empresa, string pi_timbrado)
        {
            return base.Channel.sp_get_datos_variosAsync(pi_id_empresa, pi_timbrado);
        }
        
        public string inserta_producto(
                    string tipoproceso, 
                    int codigopro, 
                    string tipoprodu, 
                    string marca, 
                    string nombre, 
                    decimal precioc, 
                    decimal preciov, 
                    double mamahouseo, 
                    string nomenclatura, 
                    decimal iva, 
                    decimal preciov2, 
                    decimal preciov3, 
                    int PI_LABORATORIO, 
                    string PI_CODIGOPRODUCTO, 
                    string PI_CODIGO_BARRA, 
                    string PI_NROLOTE, 
                    string PI_VENCIMIENTO, 
                    string PI_COMPOSICION, 
                    string PI_CONTROLADO, 
                    string PI_FRACCION, 
                    int PI_CANTCAJA, 
                    int PI_DESCUENTO, 
                    string PI_FINDESCUENTO, 
                    string PI_USUARIO, 
                    string pi_codproducto)
        {
            return base.Channel.inserta_producto(tipoproceso, codigopro, tipoprodu, marca, nombre, precioc, preciov, mamahouseo, nomenclatura, iva, preciov2, preciov3, PI_LABORATORIO, PI_CODIGOPRODUCTO, PI_CODIGO_BARRA, PI_NROLOTE, PI_VENCIMIENTO, PI_COMPOSICION, PI_CONTROLADO, PI_FRACCION, PI_CANTCAJA, PI_DESCUENTO, PI_FINDESCUENTO, PI_USUARIO, pi_codproducto);
        }
        
        public System.Threading.Tasks.Task<string> inserta_productoAsync(
                    string tipoproceso, 
                    int codigopro, 
                    string tipoprodu, 
                    string marca, 
                    string nombre, 
                    decimal precioc, 
                    decimal preciov, 
                    double mamahouseo, 
                    string nomenclatura, 
                    decimal iva, 
                    decimal preciov2, 
                    decimal preciov3, 
                    int PI_LABORATORIO, 
                    string PI_CODIGOPRODUCTO, 
                    string PI_CODIGO_BARRA, 
                    string PI_NROLOTE, 
                    string PI_VENCIMIENTO, 
                    string PI_COMPOSICION, 
                    string PI_CONTROLADO, 
                    string PI_FRACCION, 
                    int PI_CANTCAJA, 
                    int PI_DESCUENTO, 
                    string PI_FINDESCUENTO, 
                    string PI_USUARIO, 
                    string pi_codproducto)
        {
            return base.Channel.inserta_productoAsync(tipoproceso, codigopro, tipoprodu, marca, nombre, precioc, preciov, mamahouseo, nomenclatura, iva, preciov2, preciov3, PI_LABORATORIO, PI_CODIGOPRODUCTO, PI_CODIGO_BARRA, PI_NROLOTE, PI_VENCIMIENTO, PI_COMPOSICION, PI_CONTROLADO, PI_FRACCION, PI_CANTCAJA, PI_DESCUENTO, PI_FINDESCUENTO, PI_USUARIO, pi_codproducto);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_busqueda_cliente001(string v_tipo, double v_codigo, string v_documento, string v_nombre, string v_apellido)
        {
            return base.Channel.sp_busqueda_cliente001(v_tipo, v_codigo, v_documento, v_nombre, v_apellido);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_busqueda_cliente001Async(string v_tipo, double v_codigo, string v_documento, string v_nombre, string v_apellido)
        {
            return base.Channel.sp_busqueda_cliente001Async(v_tipo, v_codigo, v_documento, v_nombre, v_apellido);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_mozos()
        {
            return base.Channel.sp_mozos();
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_mozosAsync()
        {
            return base.Channel.sp_mozosAsync();
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_datos_producto(double v_id)
        {
            return base.Channel.sp_datos_producto(v_id);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_datos_productoAsync(double v_id)
        {
            return base.Channel.sp_datos_productoAsync(v_id);
        }
        
        public string sp_validacion(string PI_TIPO, string PI_CODPRODUCTO, string PI_CODBARRA, string PI_FECHA)
        {
            return base.Channel.sp_validacion(PI_TIPO, PI_CODPRODUCTO, PI_CODBARRA, PI_FECHA);
        }
        
        public System.Threading.Tasks.Task<string> sp_validacionAsync(string PI_TIPO, string PI_CODPRODUCTO, string PI_CODBARRA, string PI_FECHA)
        {
            return base.Channel.sp_validacionAsync(PI_TIPO, PI_CODPRODUCTO, PI_CODBARRA, PI_FECHA);
        }
        
        public string inserta_tipo_marca(string tipo_proceso, string id_codigo, string nombre)
        {
            return base.Channel.inserta_tipo_marca(tipo_proceso, id_codigo, nombre);
        }
        
        public System.Threading.Tasks.Task<string> inserta_tipo_marcaAsync(string tipo_proceso, string id_codigo, string nombre)
        {
            return base.Channel.inserta_tipo_marcaAsync(tipo_proceso, id_codigo, nombre);
        }
        
        public string inserta_tipo_producto(string tipo_proceso, string id_codigo, string nombre)
        {
            return base.Channel.inserta_tipo_producto(tipo_proceso, id_codigo, nombre);
        }
        
        public System.Threading.Tasks.Task<string> inserta_tipo_productoAsync(string tipo_proceso, string id_codigo, string nombre)
        {
            return base.Channel.inserta_tipo_productoAsync(tipo_proceso, id_codigo, nombre);
        }
        
        public string insertupdatecliente(string tipoproceso, string codigocliente, string nombre, string apellido, string tipo_persona, string documento, string direccion, string telefono, string email, string fechanaci, string sexo, string operarconche, string refname, string reftelef, string profesion)
        {
            return base.Channel.insertupdatecliente(tipoproceso, codigocliente, nombre, apellido, tipo_persona, documento, direccion, telefono, email, fechanaci, sexo, operarconche, refname, reftelef, profesion);
        }
        
        public System.Threading.Tasks.Task<string> insertupdateclienteAsync(string tipoproceso, string codigocliente, string nombre, string apellido, string tipo_persona, string documento, string direccion, string telefono, string email, string fechanaci, string sexo, string operarconche, string refname, string reftelef, string profesion)
        {
            return base.Channel.insertupdateclienteAsync(tipoproceso, codigocliente, nombre, apellido, tipo_persona, documento, direccion, telefono, email, fechanaci, sexo, operarconche, refname, reftelef, profesion);
        }
        
        public string sp_validaciones(string pi_tipo, string pi_parametro, string pi_sucursal)
        {
            return base.Channel.sp_validaciones(pi_tipo, pi_parametro, pi_sucursal);
        }
        
        public System.Threading.Tasks.Task<string> sp_validacionesAsync(string pi_tipo, string pi_parametro, string pi_sucursal)
        {
            return base.Channel.sp_validacionesAsync(pi_tipo, pi_parametro, pi_sucursal);
        }
        
        public void marcarpresencia()
        {
            base.Channel.marcarpresencia();
        }
        
        public System.Threading.Tasks.Task marcarpresenciaAsync()
        {
            return base.Channel.marcarpresenciaAsync();
        }
        
        public string sp_actualizaNombreFactura(string pi_tipo, string cliente, string comprobante)
        {
            return base.Channel.sp_actualizaNombreFactura(pi_tipo, cliente, comprobante);
        }
        
        public System.Threading.Tasks.Task<string> sp_actualizaNombreFacturaAsync(string pi_tipo, string cliente, string comprobante)
        {
            return base.Channel.sp_actualizaNombreFacturaAsync(pi_tipo, cliente, comprobante);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_consulta(string tipo, string datoin)
        {
            return base.Channel.sp_consulta(tipo, datoin);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_consultaAsync(string tipo, string datoin)
        {
            return base.Channel.sp_consultaAsync(tipo, datoin);
        }
        
        public string sp_anular_factura(double v_factura, double v_mesa)
        {
            return base.Channel.sp_anular_factura(v_factura, v_mesa);
        }
        
        public System.Threading.Tasks.Task<string> sp_anular_facturaAsync(double v_factura, double v_mesa)
        {
            return base.Channel.sp_anular_facturaAsync(v_factura, v_mesa);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_combos_sistema(string tipo)
        {
            return base.Channel.sp_combos_sistema(tipo);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_combos_sistemaAsync(string tipo)
        {
            return base.Channel.sp_combos_sistemaAsync(tipo);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_datos_pedido()
        {
            return base.Channel.sp_datos_pedido();
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_datos_pedidoAsync()
        {
            return base.Channel.sp_datos_pedidoAsync();
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_datos_producto1(double v_id)
        {
            return base.Channel.sp_datos_producto1(v_id);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_datos_producto1Async(double v_id)
        {
            return base.Channel.sp_datos_producto1Async(v_id);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_get_timbrados_ventas(string pi_id_empresa)
        {
            return base.Channel.sp_get_timbrados_ventas(pi_id_empresa);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_get_timbrados_ventasAsync(string pi_id_empresa)
        {
            return base.Channel.sp_get_timbrados_ventasAsync(pi_id_empresa);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_historico_caja(string v_desde, string v_hasta, string v_estado, string v_tipo, string V_SUCURSAL, string V_USUARIO)
        {
            return base.Channel.sp_historico_caja(v_desde, v_hasta, v_estado, v_tipo, V_SUCURSAL, V_USUARIO);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_historico_cajaAsync(string v_desde, string v_hasta, string v_estado, string v_tipo, string V_SUCURSAL, string V_USUARIO)
        {
            return base.Channel.sp_historico_cajaAsync(v_desde, v_hasta, v_estado, v_tipo, V_SUCURSAL, V_USUARIO);
        }
        
        public string sp_inserta_detalle(double v_fact_id, double v_produ_id, double v_menu_id, double v_fdet_cantidad, string v_fdet_descri, double v_fdet_descp, double v_fdet_descm, double v_fdet_preciou, double v_fdet_preciot, double v_fdet_ivatip, double v_fdet_gravado)
        {
            return base.Channel.sp_inserta_detalle(v_fact_id, v_produ_id, v_menu_id, v_fdet_cantidad, v_fdet_descri, v_fdet_descp, v_fdet_descm, v_fdet_preciou, v_fdet_preciot, v_fdet_ivatip, v_fdet_gravado);
        }
        
        public System.Threading.Tasks.Task<string> sp_inserta_detalleAsync(double v_fact_id, double v_produ_id, double v_menu_id, double v_fdet_cantidad, string v_fdet_descri, double v_fdet_descp, double v_fdet_descm, double v_fdet_preciou, double v_fdet_preciot, double v_fdet_ivatip, double v_fdet_gravado)
        {
            return base.Channel.sp_inserta_detalleAsync(v_fact_id, v_produ_id, v_menu_id, v_fdet_cantidad, v_fdet_descri, v_fdet_descp, v_fdet_descm, v_fdet_preciou, v_fdet_preciot, v_fdet_ivatip, v_fdet_gravado);
        }
        
        public string sp_inserta_detalle2(double v_fact_id, double v_produ_id, double v_menu_id, double v_fdet_cantidad, string v_fdet_descri, double v_fdet_descp, double v_fdet_descm, double v_fdet_preciou, double v_fdet_preciot, double v_fdet_ivatip, double v_fdet_gravado)
        {
            return base.Channel.sp_inserta_detalle2(v_fact_id, v_produ_id, v_menu_id, v_fdet_cantidad, v_fdet_descri, v_fdet_descp, v_fdet_descm, v_fdet_preciou, v_fdet_preciot, v_fdet_ivatip, v_fdet_gravado);
        }
        
        public System.Threading.Tasks.Task<string> sp_inserta_detalle2Async(double v_fact_id, double v_produ_id, double v_menu_id, double v_fdet_cantidad, string v_fdet_descri, double v_fdet_descp, double v_fdet_descm, double v_fdet_preciou, double v_fdet_preciot, double v_fdet_ivatip, double v_fdet_gravado)
        {
            return base.Channel.sp_inserta_detalle2Async(v_fact_id, v_produ_id, v_menu_id, v_fdet_cantidad, v_fdet_descri, v_fdet_descp, v_fdet_descm, v_fdet_preciou, v_fdet_preciot, v_fdet_ivatip, v_fdet_gravado);
        }
        
        public TechnicalServiceReference.ArrayOfXElement SP_LISTA_COMPRAS(string PI_TIPO, string PI_CODPRODUCTO, string PI_DESDE, string PI_HASTA)
        {
            return base.Channel.SP_LISTA_COMPRAS(PI_TIPO, PI_CODPRODUCTO, PI_DESDE, PI_HASTA);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> SP_LISTA_COMPRASAsync(string PI_TIPO, string PI_CODPRODUCTO, string PI_DESDE, string PI_HASTA)
        {
            return base.Channel.SP_LISTA_COMPRASAsync(PI_TIPO, PI_CODPRODUCTO, PI_DESDE, PI_HASTA);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_listado_categorias(string pi_tipo, string pi_codigo)
        {
            return base.Channel.sp_listado_categorias(pi_tipo, pi_codigo);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_listado_categoriasAsync(string pi_tipo, string pi_codigo)
        {
            return base.Channel.sp_listado_categoriasAsync(pi_tipo, pi_codigo);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_reporte_producto1(int tipo_consulta, double pi_producto, double pi_marca, string pi_descripcion)
        {
            return base.Channel.sp_reporte_producto1(tipo_consulta, pi_producto, pi_marca, pi_descripcion);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_reporte_producto1Async(int tipo_consulta, double pi_producto, double pi_marca, string pi_descripcion)
        {
            return base.Channel.sp_reporte_producto1Async(tipo_consulta, pi_producto, pi_marca, pi_descripcion);
        }
        
        public void sp_perdidas(string pi_tipo, string pi_codproducto, string pi_cantidadactual, string pi_cantidadnueva, string pi_diferencia, string pi_sucursal, string pi_usuario)
        {
            base.Channel.sp_perdidas(pi_tipo, pi_codproducto, pi_cantidadactual, pi_cantidadnueva, pi_diferencia, pi_sucursal, pi_usuario);
        }
        
        public System.Threading.Tasks.Task sp_perdidasAsync(string pi_tipo, string pi_codproducto, string pi_cantidadactual, string pi_cantidadnueva, string pi_diferencia, string pi_sucursal, string pi_usuario)
        {
            return base.Channel.sp_perdidasAsync(pi_tipo, pi_codproducto, pi_cantidadactual, pi_cantidadnueva, pi_diferencia, pi_sucursal, pi_usuario);
        }
        
        public double f_usuario_login(string pi_usuario, string pi_password)
        {
            return base.Channel.f_usuario_login(pi_usuario, pi_password);
        }
        
        public System.Threading.Tasks.Task<double> f_usuario_loginAsync(string pi_usuario, string pi_password)
        {
            return base.Channel.f_usuario_loginAsync(pi_usuario, pi_password);
        }
        
        public string SP_MENSAJE(string pi_cliente, string pi_usuario)
        {
            return base.Channel.SP_MENSAJE(pi_cliente, pi_usuario);
        }
        
        public System.Threading.Tasks.Task<string> SP_MENSAJEAsync(string pi_cliente, string pi_usuario)
        {
            return base.Channel.SP_MENSAJEAsync(pi_cliente, pi_usuario);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_usuario_sel(string v_usuario)
        {
            return base.Channel.sp_usuario_sel(v_usuario);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_usuario_selAsync(string v_usuario)
        {
            return base.Channel.sp_usuario_selAsync(v_usuario);
        }
        
        public double sp_usuario_updpas(string pi_usuario, string pi_password)
        {
            return base.Channel.sp_usuario_updpas(pi_usuario, pi_password);
        }
        
        public System.Threading.Tasks.Task<double> sp_usuario_updpasAsync(string pi_usuario, string pi_password)
        {
            return base.Channel.sp_usuario_updpasAsync(pi_usuario, pi_password);
        }
        
        public string sp_usuario(string pi_tipo, string pi_usuario)
        {
            return base.Channel.sp_usuario(pi_tipo, pi_usuario);
        }
        
        public System.Threading.Tasks.Task<string> sp_usuarioAsync(string pi_tipo, string pi_usuario)
        {
            return base.Channel.sp_usuarioAsync(pi_tipo, pi_usuario);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_lista_facturas(string v_desde, string v_hasta, string v_tipo, string usuario, string sucursal)
        {
            return base.Channel.sp_lista_facturas(v_desde, v_hasta, v_tipo, usuario, sucursal);
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_lista_facturasAsync(string v_desde, string v_hasta, string v_tipo, string usuario, string sucursal)
        {
            return base.Channel.sp_lista_facturasAsync(v_desde, v_hasta, v_tipo, usuario, sucursal);
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_tipos_usuarios()
        {
            return base.Channel.sp_tipos_usuarios();
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_tipos_usuariosAsync()
        {
            return base.Channel.sp_tipos_usuariosAsync();
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_estados_usuarios()
        {
            return base.Channel.sp_estados_usuarios();
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_estados_usuariosAsync()
        {
            return base.Channel.sp_estados_usuariosAsync();
        }
        
        public TechnicalServiceReference.ArrayOfXElement sp_lista_usuarios()
        {
            return base.Channel.sp_lista_usuarios();
        }
        
        public System.Threading.Tasks.Task<TechnicalServiceReference.ArrayOfXElement> sp_lista_usuariosAsync()
        {
            return base.Channel.sp_lista_usuariosAsync();
        }
        
        public string sp_usuario_ins(string pi_usuario, string pi_apellido, string pi_password, string pi_cedula, int pi_nivel, string pi_telef, int pi_estado, string sucursal)
        {
            return base.Channel.sp_usuario_ins(pi_usuario, pi_apellido, pi_password, pi_cedula, pi_nivel, pi_telef, pi_estado, sucursal);
        }
        
        public System.Threading.Tasks.Task<string> sp_usuario_insAsync(string pi_usuario, string pi_apellido, string pi_password, string pi_cedula, int pi_nivel, string pi_telef, int pi_estado, string sucursal)
        {
            return base.Channel.sp_usuario_insAsync(pi_usuario, pi_apellido, pi_password, pi_cedula, pi_nivel, pi_telef, pi_estado, sucursal);
        }
        
        public string sp_usuario_upd(string pi_usuario, string pi_apellido, string pi_password, string pi_cedula, int pi_nivel, string pi_telef, int pi_estado, string sucursal)
        {
            return base.Channel.sp_usuario_upd(pi_usuario, pi_apellido, pi_password, pi_cedula, pi_nivel, pi_telef, pi_estado, sucursal);
        }
        
        public System.Threading.Tasks.Task<string> sp_usuario_updAsync(string pi_usuario, string pi_apellido, string pi_password, string pi_cedula, int pi_nivel, string pi_telef, int pi_estado, string sucursal)
        {
            return base.Channel.sp_usuario_updAsync(pi_usuario, pi_apellido, pi_password, pi_cedula, pi_nivel, pi_telef, pi_estado, sucursal);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://15.222.249.125:1501/ws_technical/Service1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://15.222.249.125:1501/ws_technical/Service1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Service1Soap,
            
            Service1Soap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.0.0.2")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
